import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import State from 'App/Models/State'

const states = [
  {
    id: 11,
    abbreviation: 'RO',
    name: 'Rondônia',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 12,
    abbreviation: 'AC',
    name: 'Acre',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 13,
    abbreviation: 'AM',
    name: 'Amazonas',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 14,
    abbreviation: 'RR',
    name: 'Roraima',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 15,
    abbreviation: 'PA',
    name: 'Pará',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 16,
    abbreviation: 'AP',
    name: 'Amapá',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 17,
    abbreviation: 'TO',
    name: 'Tocantins',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 21,
    abbreviation: 'MA',
    name: 'Maranhão',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 22,
    abbreviation: 'PI',
    name: 'Piauí',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 23,
    abbreviation: 'CE',
    name: 'Ceará',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 24,
    abbreviation: 'RN',
    name: 'Rio Grande do Norte',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 25,
    abbreviation: 'PB',
    name: 'Paraíba',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 26,
    abbreviation: 'PE',
    name: 'Pernambuco',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 27,
    abbreviation: 'AL',
    name: 'Alagoas',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 28,
    abbreviation: 'SE',
    name: 'Sergipe',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 29,
    abbreviation: 'BA',
    name: 'Bahia',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 31,
    abbreviation: 'MG',
    name: 'Minas Gerais',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 32,
    abbreviation: 'ES',
    name: 'Espírito Santo',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 33,
    abbreviation: 'RJ',
    name: 'Rio de Janeiro',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 35,
    abbreviation: 'SP',
    name: 'São Paulo',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 41,
    abbreviation: 'PR',
    name: 'Paraná',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 42,
    abbreviation: 'SC',
    name: 'Santa Catarina',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 43,
    abbreviation: 'RS',
    name: 'Rio Grande do Sul',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 50,
    abbreviation: 'MS',
    name: 'Mato Grosso do Sul',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 51,
    abbreviation: 'MT',
    name: 'Mato Grosso',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 52,
    abbreviation: 'GO',
    name: 'Goiás',
    createdById: 1,
    lastEditById: 1,
  },
  {
    id: 53,
    abbreviation: 'DF',
    name: 'Distrito Federal',
    createdById: 1,
    lastEditById: 1,
  },
]

export default class extends BaseSeeder {
  public async run() {
    await State.createMany(states)
  }
}
