version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=tcc
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060

volumes:
  mariadb_data:
